const { create } = require('domain');
const fs = require('fs');
var path = require('path');
var crypto = require('crypto');

var walk = function(dir, done) {
  var results = [];
  fs.readdir(dir, function(err, list) {
    if (err) return done(err);
    var pending = list.length;
    if (!pending) return done(null, results);
    list.forEach(function(file) {
      file = path.resolve(dir, file);
      fs.stat(file, function(err, stat) {
        if (stat && stat.isDirectory()) {
          walk(file, function(err, res) {
            results = results.concat(res);
            if (!--pending) done(null, results);
          });
        } else {
          results.push(file);
          if (!--pending) done(null, results);
        }
      });
    });
  });
};

walk('./Macros', function(err, results) {
    if (err) throw err;
    var scripts = [];
    var names = [];
    results.forEach(file => {
        if (file.endsWith('.js')) {
            console.log(file);
            scripts.push(convertFile(file));
            names.push(file.split('/').pop().split('.')[0]);
        }
    });
    createFile(scripts, names);
});

function convertFile(file){
    fs.readFile(file, 'utf8', function(err, data){
        if (err) {
            return console.log(err);
        }
        return data;
    });
}

function generateRandomID() {
    return new Promise((res) => {
        crypto.randomBytes(12, (err, buf) => {
            if(err) throw err;
            const enc = buf.toString('base64');
            if(enc.length !== 16) throw 'invalid';
            res(enc);
        });
    });
}

function writeFile(file){
    fs.writeFile('./packs/scripts.db', file, err =>{
        if(err) {
            return console.log(err);
        }
        console.log("The file was saved!");
    });
}

function createFile(scripts, names){
    var file = `// This file was generated by a script. Do not edit.\n`;
    var uuid = "";
    generateRandomID().then(id => {uuid = id}).catch(err => {console.log(err)});
    uuid = uuid.replace(/=/g, '');
    for (i = 0; i < scripts.length; i++){
        var name = names[i].charAt(0).toUpperCase() + names[i].slice(1);
        var filecontents = {"name": name,"permission": {"default": 2},"type": "script","_id": uuid,"scope": "global","img": "assets/icons/"+names[i]+".svg","folder": "null","_stats": {"system": "shadowrun5e"},"command": scripts[i]};
        file += JSON.stringify(filecontents)+"\n";
    }
    writeFile(file);
}