name: Convert Macros

on:
    pull_request:
      branches:
        - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Convert Macros
              run: |
                    npm install
                    node convert.js
            - name: Commit changes
              run: |
                    git config --local user.email "