name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update settings.json url
        uses: jossef/action-set-json-field@v2.1
        with:
          file: module.json
          field: url
          value: https://github.com/${{github.repository}}
      - name: Update settings.json bugs
        uses: jossef/action-set-json-field@v2.1
        with:
          file: module.json
          field: bugs
          value: https://github.com/${{github.repository}}/issues
      - name: Update settings.json manifest
        uses: jossef/action-set-json-field@v2.1
        with:
          file: module.json
          field: manifest
          value: https://github.com/${{github.repository}}/releases/latest/download/module.json
      - name: Update settings.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: module.json
          field: version
          value: ${{github.event.release.tag_name}}
      - name: Update settings.json download
        uses: jossef/action-set-json-field@v2.1
        with:
          file: module.json
          field: download
          value: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.zip

      # Create zip file
      - run: zip -r ./module.zip module.json LICENSE packs/ README.md

      # Create a release for this specific version.
      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GH_TOKEN }}
          artifacts: "./module.json, ./module.zip"
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
